### ISSUE TITLE
Install Scripts security improvements

### ISSUE THREAD

**Issue by YuliiaKovalova** [dotnet/install-scripts#503]
The security work that needs to be done:

- [x] - ~.Net vulnerabilities (https://github.com/dotnet/install-scripts/issues/500)~ Not actionable now due to https://github.com/dotnet/install-scripts/issues/500#issuecomment-2258934790
- [x]  - Publishing to BAR/Maestro will no longer support tokens (https://github.com/dotnet/install-scripts/issues/502)
- [x] - CG (https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-install-scripts/alert/9974784?typeId=6427340) (in scope of https://github.com/dotnet/install-scripts/pull/504 and https://github.com/dotnet/install-scripts/pull/506 )
