### ISSUE TITLE
Maintenance Mode Prerequisites

### ISSUE THREAD

**Issue by bozturkMSFT** [dotnet/install-scripts#88]
We plan to deliver the following items before we go into maintenance mode.

- [x] #72 - Installation on Alpine misses some prerequisites, so dotnet won't   run
- [x] #65 - Consume version metadata   files to ensure picking up the right build from each channel
- [ ] #12 - Add support for aka.ms   links for dotnet-install
- [x] #16 - SH installs wrong   architecture on ARM64 host, ARM32 OS
- [x] #38 - Update repo in script's exception URLs
- [x] #43 - Review documentation for   when the install scripts are to be used
- [x] #36 - Requiring tools (libcurl)   that are not needed
- [x] #6 - dotnet-install.sh   dependency checks are incorrect
- [x] #25 - dotnet-install script   causes shell to exit
- [x] #29 - Powershell Install Script Custom Path Error
- [x] #11 - Clarify that 404 at   "downloading legacy link" in dotnet-install.sh is usually expected
- [x] #7 - SH doesn't correctly grab   global.json sdk version
- [x] #8 - dotnet-install fails with   Exception calling invoke with 0 arguments
- [x] #64 - `-Channel master -Version   coherent` downloads 3.0, not 5.0
- [x] #27 - PS1 failed without error   diagnosis
- [x] #9 - Script fails to access the   feed if TLS1.2 is not enabled (log some warning atleast)
- [x] #28 - dotnet/cli     dotnet-install-sh  3.1.100  --runtime variations (run with Kathleen)
- [x] #13 - Use of --runtime-id generates incorrect   primary URL (run with Kathleen)
- [x] #45 - Repeated invocations of dotnet-install.sh   will fill TMP directory (run with Kathleen)
- [ ] #122 - Update docs.microsoft.com for latest changes
- [ ] #116 - Change the path for windows desktop runtime packages

**Comment by bozturkMSFT** [comment]
All the changes to be done in this repository regarding the maintenance tasks has been completed. Closing this epic.
